services:
  - type: web
    name: classis-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
